# wrangler.toml - CORREGIDO
name = "procedimiento-cambios-devoluciones" # <-- CAMBIADO a minúsculas y con guiones
compatibility_date = "2025-04-27" # Usa una fecha válida/reciente

[site]
bucket = "." # <-- Esto debería estar bien si tus archivos están en la raíz