name = "ProcedimientoCambiosDevoluciones" # O el nombre que prefieras
compatibility_date = "2025-04-27" # Puedes usar la fecha actual o una reciente

[site]
bucket = "." # <-- ¡Este es el cambio clave! El punto "." significa "el directorio actual" (la raíz del proyecto)